name: Quarto Build Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3 # v3 is the third major version of actions/checkout

      # Set up Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'latest'

      # Compile Quarto site and check for compiling errors
      - name: Check if Quarto site compiles
        run: |
          quarto render .

      # Notify if compiling fails
      - name: Notify failure
        if: failure()
        run: echo "Quarto site failed to compile."